### ISSUE TITLE
Parameter spinboxes in Python GUI:  Ensure coherens between the formats of the values given in the 'info-window' and the formats of the values displayed in the corresponding 'parameter spinboxes'. 

### ISSUE THREAD

**Issue by janhenrikwold** [ifarup/tc1-82#103]
-- When the number(s) in the 'symbol subscripts', 'domain spesification' or 'step specification' are to be displayed as integer(s) in the 'info-window', let the value(s) given in the corresponding parameter spinbox(es) also be displayed as  integer number(s). 
-- When the number(s) in the 'symbol subscripts', 'domain spesification' or 'step specification' are to be displayed as decimal number(s) in the 'info-window', let the value(s) given in the corresponding parameter spinbox(es) also be displayed as decimal number(s). 
(i.e., if necessary for coherens with the format of the value in the info-window, auto-correct the value given in the corresponding parameter spin box from decimal number to integer, or vice versa.)

This is a general Issue in the Python GUI.

**Comment by ifarup** [comment]
This was solved along with #104 .
