### ISSUE TITLE
Spinbox for 'Upper domain limit' in Python GUI: Auto-correct vaule to be consistent with parameter choices for 'lower domain limit' and 'step'.  

### ISSUE THREAD

**Issue by janhenrikwold** [ifarup/tc1-82#104]
If there is no mathematical consistency between the values given in the parameter spinboxes for 'lower domain limit', 'upper domain limit' and 'step', auto-correct the value given in the 'parameter spin box' for the  'upper domain limit' to the largest number satisfying

'lower domain limit' + n 'step' < 'upper domain limit' ,    where  n is an integer.

In doing this, check also #102.

**Comment by ifarup** [comment]
After a long discussion, we (Gerardo and I) have decided on the following GUI behaviour: The three parameters lambda_min, lambda_max and lambda_step are adjusted individually by the user in steps of 0.1 nm. Only when compute is pressed the parameters are sent to compute, which changes the lambda_max parameter if necessary. If lambda_max is changed, the value of the spinbox is also changed. This is the best we can do.
