### ISSUE TITLE
In Python GUI:  The values in the spinbox for lambda_min is not autocorrected correctly

### ISSUE THREAD

**Issue by janhenrikwold** [ifarup/tc1-82#168]
When the user, by means of the keyboard, set lambda_min<390, the value displayed in the spinbox should be autocorrected to 390. The autocorrection instead returns the lamda_min from the preceeding computation.

**Comment by ifarup** [comment]
This is a Qt bug/feature/standard behaviour, not caused by our code. Have to keep it.
