### ISSUE TITLE
In Python GUI: Spinbox for lambda_max should allow keybord setting > 830, but should autocorrect this to 830 on compute

### ISSUE THREAD

**Issue by janhenrikwold** [ifarup/tc1-82#169]
Trying to set the lambda_max spinbox value to e.g. 850, only 85 is displayed. It should be allowed, however, to give a lambda_max value of 850, but this should then be autocorrected to 830 on compute.

See also #168 and #154

**Comment by ifarup** [comment]
This is a Qt bug/feature/restriction, not caused by our code.
