### ISSUE TITLE
Web-app: In the MS Internet explorer browser, in particular, fix wrong posision of  axis label for the ordinate axis

### ISSUE THREAD

**Issue by janhenrikwold** [ifarup/tc1-82#66]
The plot-windows seem to be interrupted, and the appearance of the info-windows needs to be improved (at least in my version of MS Internet Explorer (vs 8.0.7601.17514 (64-bit Edition)).

**Comment by gerardodiego** [comment]
http://au.ibtimes.com/microsoft-discontinue-internet-explorer-launch-new-browser-windows-10-1430604

There is no point on prioritising this, imho.
